# Site settings
title: "ShanLunjiaJian's Blog"
SEOTitle: "ShanLunjiaJian's Blog"
header-img: img/bg.png
email: "1391137786@qq.com"
description: "sd初三菜鸡OIer ShanLunjiaJian的blog"
keyword: "ShanLunjiaJian"
url: "https://shanlunjiajian.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: false

# SNS settings
RSS: false
github_username: ShanLunjiaJian
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
# plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "sdjn sdfz高一菜鸡OIer"
sidebar-avatar: /img/photo.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: true



# Friends

friends: [
    {
        title: "fireinice",
        href: "https://www.jianshu.com/u/91bc345f7c84"
    },{
        title: "Pbri",
        href: "https://www.luogu.com.cn/blog/rubik-aoyi715103/"
    },{
        title: "SD!LTF",
        href: "https://www.cnblogs.com/sdltf"
    },{
        title: "dbxxx",
        href: "https://www.cnblogs.com/crab-in-the-northeast"
    },{
        title: "Return.",
        href: "https://www.cnblogs.com/return-blog"
    },{
        title: "jzk",
        href: "https://www.cnblogs.com/ZhengkunJia"
    },{
        title: "Coelacanthus",
        href: "https://blog.lhwcrt.top/"
    },{
        title: "_zkw",
        href: "https://www.luogu.com.cn/blog/lry/"
    },{
        title: "Refined_heart",
        href: "https://www.cnblogs.com/h-lka/"
    },{
        title: "Sxy_Limit",
        href: "https://www.cnblogs.com/Sxy_Limit/"
    },{
        title: "tommy0103",
        href: "https://www.luogu.com.cn/blog/fzber0103/"
    },{
        title: "YoungTom",
        href: "https://www.luogu.com.cn/user/192773"
    },{
        title: "fty",
        href: "https://www.luogu.com.cn/blog/ljfty666666666666/"
    },{
        title: "Var1ous",
        href: "https://www.luogu.com.cn/blog/Rout-Execut0r/"
    },{
        title: "Histone",
        href: "http://47.102.209.15/"
    },{
        title: "sdsy2020147",
        href: "https://www.luogu.com.cn/user/179182"
    },{
        title: "cunzai_zsy0531",
        href: "https://www.luogu.com.cn/user/160484"
    },{
        title: "knifebrother",
        href: "https://www.luogu.com.cn/user/150555"
    },{
        title: "Syx",
        href: "http://49.232.134.133/"
    },{
        title: "do_while_true",
        href: "https://cnblogs.com/do-while-true/"
    },{
        title: "Virtualman",
        href: "http://virtualman.top"
    },{
        title: "q0000000",
        href: "https://www.luogu.com.cn/user/356120"
    },{
        title: "绝顶我为峰",
        href: "https://www.cnblogs.com/Forza-Ferrari/"
    },{
        title: "lytqwq",
        href: "https://www.luogu.com.cn/user/104319"
    },{
        title: "vectorwyx",
        href: "https://www.luogu.com.cn/blog/dream-of-Au/"
    },{
        title: "suxxsfe",
        href: "https://www.cnblogs.com/suxxsfe/"
    },{
        title: "lindongli2004",
        href: "https://www.luogu.com.cn/blog/lindongli2004/"
    }
]

gitalk_client_id: '06b7efda61742d7e5a44'
gitalk_client_secret: '297d5ae3c7558d570bc3deead920d58ad298c302'
gitalk_repo: 'shanlunjiajian.github.io'
gitalk_owner: 'ShanLunjiaJian'
gitalk_admin: ["ShanLunjiaJian","pbrinotwyh","suxxsfe"]